# Permalinks
permalink:        pretty


# Setup
title:            Blog
tagline:          by Kunyao Chen
url:              http://kunyao.github.io
paginate:         1
baseurl:          /
author:
  name:           Kunyao Chen
  url:            http://kunyao.github.io
  email:          funtionyao32@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/kunyao/kunyao.github.io.git
